config/routes.rb
Foodlist::Application.routes.draw do
  root to: "welcome#index"
  ActiveAdmin.routes(self)
  break if ARGV.join.include? 'assets:precompile'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", users_controller: "users_controller"}

  scope module: 'authenticated' do
    resources :items do
      resources :comments, except: [:edit, :update] do
        get "like", to: "comments#like", on: :member
        get "dislike", to: "comments#dislike", on: :member
      end 
      get "like", to: "items#like"
      get "dislike", to: "items#dislike"
    end
    resources :comments, only: [:update]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  after_create :send_notification

  CATEGORIES = ["food", "office", "bathroom", "other"]

  #Voting
  acts_as_votable

  # Assosiations
  belongs_to :user
  has_many :comments

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :URL, :format => URI::regexp(%w(http https)), allow_blank: true
  
  scope :recent_first, -> { order('items.created_at DESC') }

  def send_notification
    NotificationMailer.new_item(self).deliver
  end

  def self.highest_voted
    self.order("items.cached_votes_score DESC")
  end
end

app/controllers/authenticated/base_controller.rb
class Authenticated::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/authenticated/comments_controller.rb
class Authenticated::CommentsController < Authenticated::BaseController
  before_filter :fetch_item, except: [:edit, :update]
  before_filter :fetch_comment, only: [:destroy, :like, :dislike]

  def create
    @comment = current_user.comments.new(comment_params)
 
    @comment.item = @item
    if @comment.save
      redirect_to item_path(@item), notice: I18n.t('flash.authenticated.comments.create.notice')
    else
      redirect_to item_path(@item), alert: I18n.t('flash.authenticated.comments.create.alert')
    end
  end


  def update
    @comment = current_user.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.json { respond_with_bip(@comment) }
      else
        format.json { respond_with_bip(@comment) }
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to @item, notice: 'Comment was deleted'
  end

  # Voting

  def like
    @comment.upvote_from current_user
    redirect_to @item
  end

  def dislike
    @comment.downvote_from current_user
    redirect_to @item
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :item_id, :user_id, :parent_id)
  end

  def fetch_item  
    @item = Item.find(params[:item_id])
  end

  def fetch_comment
    @comment = @item.comments.find(params[:id])
  end
end

# .merge(:parent_id => params[:parent_id])

app/controllers/authenticated/items_controller.rb
class Authenticated::ItemsController < Authenticated::BaseController
  respond_to :html, :json

  before_filter :find_item!, only: [ :update, :destroy ]

  def index
    @items = Item.all.page(params[:page]).recent_first
    @item  = Item.new
  end

  def show
    @item = Item.find(params[:id])
    @comments = @item.comments.to_a
    @comment = Comment.new(params[:comment_params])
  end

  def create
    @item = current_user.items.create(item_params)
    if @item.persisted?
      redirect_to @item, notice: I18n.t('flash.authenticated.items.create.notice')
    else
      redirect_to @item, alert: I18n.t('flash.authenticated.items.create.alert')
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.json { respond_with_bip(@item) }
      else
        format.json {  respond_with_bip(@item) }
      end
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: I18n.t('flash.authenticated.items.delete')
  end

  # Voting

  def like
    @item = Item.find_by_id(params[:item_id])
    @item.upvote_from current_user
    redirect_to items_path
  end

  def dislike
    @item = Item.find_by_id(params[:item_id])
    @item.downvote_from current_user
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :URL, :category, :amount)
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end

  def find_item!
    @item = current_user.items.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/authenticated/items/_item.haml
%div{:id => "item-#{item.id}", :class => "item #{item.category}"}

  = link_to item_path(item), class: "item-link" do
    = item.name

  .item-options
    -if item.comments.count == 1
      #{item.comments.count} comment
    -else
      #{item.comments.count} comments
      / item.comments.count + (item.comments.count ==1 ? : " comment" : " comments")
    - if item.user_id == current_user.id
      = link_to edit_item_path(item), id: "edit-item-#{item.id}" do
        %i.icon-pencil
      = link_to item_path(item), id: "destroy-item-#{item.id}", method: 'delete' do
        %i.icon-trash
    - else
      = item.upvotes.size
      = link_to item_like_path(item), method: :get do
        %i.icon-thumbs-up
      = link_to item_dislike_path(item), method: :get do
        %i.icon-thumbs-down
      = 0 - item.downvotes.size

/ %table
/   %tr
/     %th= "name"
/     %th= "comments"
/     %th= "Likes"
/     %th= "Disikes"
/   - for item in @items
/     %tr
/       %td= item.name
/       %td= item.comments.count
/       %td= item.cached_votes_up
/       %td= item.cached_votes_down

app/views/authenticated/items/_tablesorter_pager.haml
.center  
  #pager.pager
    %form
      %img.first{src: "/images/pager/first.png"}/
      %img.prev{src: "/images/pager/prev.png"}/
      %input.pagedisplay{type: "text"}/
      %img.next{src: "/images/pager/next.png"}/
      %img.last{src: "/images/pager/last.png"}/
      %select.pagesize
        %option{selected: "selected", value: "10"} 10 items
        %option{value: "15"} 15 items
        %option{value: "20"} 20 items
        %option{value: "25"} 25 items
        %option{value: "30"} 30 items
        %option{value: "35"} 35 items
        %option{value: "40"} 40 items

app/views/authenticated/items/edit.html.haml
.center.span6
  %h2 Editing item
  #edit-item.well.span5
    = simple_form_for @item, html: { id: 'edit-item', class: 'form-horizontal' } do |form|
      = form.input :name, required: true, placeholder: t('authenticated.items.edit.name.input_placeholder'), input_html: { class: 'span5' }
      = form.input :URL, required: false, placeholder: t('authenticated.items.edit.url.input_placeholder'), input_html: { class: 'span5' }
      %br
      .edit-item
        .center
          Choose the category
          = select_tag "category", options_for_select([ ["food", { class: 'label label-success' }], ["office", { class: 'label label-important' }], ["bathroom", { class: 'label label-info' }], ["other", { class: 'label label-inverse' }] ])
        %br
        = form.input :amount, required: true
        %br
      = form.submit t('authenticated.items.item.edit'), class: 'btn btn-success', data: { disable_with: t('common.please_wait') }

app/views/authenticated/items/index.html.haml
#auth-info
  You are logged in as
  %b 
    %u
      = current_user.name
  %p
%table#items.tablesorter
  %thead
    %tr
      %th
      %th.header= "Name"
      %th.header= "Amount"
      %th.header= "Comments"
      %th.header= "Likes" 
      %th.header= "Dislikes"
  %tbody
    - @items.each do |item|
      %tr{ :class => "item #{item.category}"}
        %td.opt
          - if item.user_id == current_user.id
            = link_to item_path(item), id: "edit-item-#{item.id}" do
              %i.icon-pencil
            = link_to item_path(item), id: "destroy-item-#{item.id}", method: 'delete' do
              %i.icon-trash
          - else
            = link_to item_like_path(item), method: :get do
              %i.icon-thumbs-up
            = link_to item_dislike_path(item), method: :get do
              %i.icon-thumbs-down
        %td.name
          = link_to(item.name, item)
        %td.narrow 
          = item.amount
        %td.narrow= link_to(item.comments.count, item)
        %td.narrow.voters
          = item.upvotes.count
          #who-voted
            - item.votes.up.by_type(User).voters.each do |item|
              %div
                -if item.name == current_user.name
                  You,
                -else
                  =item.name + ','
        %td.narrow.voters
          = 0 - item.downvotes.size
          #who-voted
            - item.votes.down.by_type(User).voters.each do |item|
              %div
                -if item.name == current_user.name
                  You,
                -else
                  =item.name + ','
                  
/ =render :partial => 'tablesorter_pager'

.legend-wrapper
  %table#legend
    %thead
      %tr
        %th.food
        %th.office
        %th.bathroom
        %th.other
    %tbody
      %tr
        %td= 'food'
        %td= 'office'
        %td= 'bathroom'
        %td= 'other'

  = link_to nil, id: 'new-item-container', class: 'btn btn-danger' do
    = icon_label 'icon-plus', t('authenticated.items.add_item')

#new-item.well.span5
  = simple_form_for @item, html: { class: 'form-horizontal' } do |form|
    = form.input :name, remote: true, placeholder: t('authenticated.items.item.name.input_placeholder'), input_html: { class: 'span5' }, required: true
    %br
    = form.input :URL, label: "URL", remote: true, placeholder: t('authenticated.items.item.url.input_placeholder'), input_html: { class: 'span5' }
    .item
      = form.input :category, :as => :select, collection: Item::CATEGORIES, default: "food"
    = form.input :amount, required: true
    %br
    = form.submit t('common.submit'), class: 'btn btn-success', remote: true, data: { disable_with: t('common.please_wait') }

app/views/authenticated/items/show.html.haml
#auth-info
  You are logged in as
  %b 
    %u
      = current_user.name
#item-name
  = best_in_place_if @item.user == current_user, @item, :name
#request-info
  %strong
    = @item.user.name
  requested this item
  = time_ago_in_words(@item.created_at) 
  ago
  (#{@item.created_at.strftime("%d %b %y")})
  %br
  Amount: 
  = best_in_place_if @item.user == current_user, @item, :amount
  - unless @item.URL.blank?
    Link: 
    =link_to @item.URL, @item.URL, target: "_blank"
  %br
%hr
- if @comments.count == 1
  There is 1 comment to this item
- elsif @comments.count > 0
  There are #{@comments.count} comments on this item
- else
  There are no comments yet. 
%hr
  - @comments.each do |comment|
    -if comment.is_root?
      %strong
        = comment.user.name
      wrote on #{comment.created_at.strftime("%d %b %y")}:
      %br
      #root-comment
        = best_in_place_if comment.user == current_user, comment, :content, type: :textarea
      .comment-options
        - if comment.user_id == current_user.id #only author can edit and delete comment
          - if comment.children.count == 0 #can delete comment only if noone replied
            = link_to item_comment_path(@item, comment), id: "destroy-comment-#{comment.id}", method: 'delete' do
              %i.icon-trash
        - else
          = comment.upvotes.size
          = link_to like_item_comment_path(@item, comment), method: :get do
            %i.icon-thumbs-up
          = link_to dislike_item_comment_path(@item, comment), method: :get do
            %i.icon-thumbs-down
          = 0 - comment.downvotes.size
      
        = link_to nil, class: 'new-comment-container'  do
          = icon_label 'icon-reply'
        .comment-reply
          = simple_form_for [@item, @comment],  html: { class: 'form-horizontal' } do |form|
            = form.text_area :content, remote: true
            = form.hidden_field :parent_id, remote: true, value: comment.id
            %br
            %br
            = form.submit t('common.submit'), class: 'btn btn-success', remote: true, data: { disable_with: t('common.please_wait') }
        -comment.children.each do |nested_comment| #display all comment's children
          #nested-comment
            %p
            %strong
              = nested_comment.user.name
            wrote on #{comment.created_at.strftime("%d %b %y")}:
            %br
            #nested-comment-content
              = best_in_place_if nested_comment.user == current_user, nested_comment, :content, type: :textarea
            .comment-options
              - if nested_comment.user_id == current_user.id
                - if comment.children.count == 0 #can delete comment, if noone replied
                  = link_to item_comment_path(@item, nested_comment), id: "destroy-comment-#{comment.id}", method: 'delete' do
                    %i.icon-trash
                = link_to item_comment_path(@item, nested_comment), id: "destroy-comment-#{comment.id}", method: 'delete' do
                  %i.icon-trash
              - else
                = nested_comment.upvotes.size
                = link_to like_item_comment_path(@item, nested_comment), method: :get do
                  %i.icon-thumbs-up
                = link_to dislike_item_comment_path(@item, nested_comment), method: :get do
                  %i.icon-thumbs-down
                = 0 - nested_comment.downvotes.size

              = link_to nil, class: 'new-comment-container'  do
                = icon_label 'icon-reply'
              .comment-reply
                = simple_form_for [@item, @comment],  html: { class: 'form-horizontal' } do |form|
                  = form.text_area :content, remote: true
                  = form.hidden_field :parent_id, remote: true, value: comment.id
                  %br
                  %br
                  = form.submit t('common.submit'), class: 'btn btn-success', remote: true, data: { disable_with: t('common.please_wait') }
  
%hr
= render partial: '/authenticated/comments/new'

.center
  %hr
  = link_to 'Back to the list of items', {action:'index'}, class: 'important'
  %hr